# Generated by Django 3.2.7 on 2021-09-10 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='조용재', max_length=20)),
                ('birthdate', models.DateTimeField(default=datetime.date(2002, 2, 5))),
                ('hackingnickname', models.CharField(default='An4hoNYJ0', max_length=100)),
                ('selfintroducteion', models.TextField(default='Tony Stark가 되고싶은 컴공과생.🤩\n그래서 이름도 anThONY로 지었다는 소문이.. 있지만 사실은 아니라고 한다. 하핳')),
            ],
        ),
    ]
